export type CityData = {
  slug: string;
  name: string;
  region: string;
  postcodes: string;
  areas: string;
  description: string;
  intro: string;
  whyUs: string;
  faq1Q: string;
  faq1A: string;
  faq2Q: string;
  faq2A: string;
};

export const cities: CityData[] = [
  {
    slug: "birmingham",
    name: "Birmingham",
    region: "West Midlands",
    postcodes: "B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15",
    areas: "Solihull, Sutton Coldfield, Edgbaston, Erdington, Handsworth, Moseley, Kings Heath, Selly Oak",
    description: "Cheap car recovery in Birmingham & West Midlands. 24/7 breakdown assistance, towing, and roadside help across all Birmingham postcodes.",
    intro: "Breaking down in Birmingham can be stressful — from the busy M6 corridor to the city centre ring road. Our Birmingham recovery agents are positioned across the West Midlands to reach you fast, whether you're stuck on the A38, the M5, or a quiet suburban street in Edgbaston. We cover every Birmingham postcode with no hidden fees and fixed pricing.",
    whyUs: "With multiple recovery vehicles stationed across Birmingham and the wider West Midlands, we consistently achieve some of the fastest response times in the region. Our agents cover Solihull, Sutton Coldfield, Erdington, Moseley, Selly Oak, Handsworth and everywhere in between — so wherever your car lets you down in Birmingham, help is never far away.",
    faq1Q: "How much does car recovery cost in Birmingham?",
    faq1A: "Our Birmingham car recovery quotes start from a fixed price based on distance and vehicle type. Use our instant quote form above to get your exact price before you commit — no surprises, no call-out fees.",
    faq2Q: "Do you cover motorways near Birmingham?",
    faq2A: "Yes. We assist on the M6, M5, M42, and A38(M) — all major routes in and around Birmingham. If you've broken down on a motorway, stay in your vehicle with hazard lights on and call us immediately.",
  },
  {
    slug: "manchester",
    name: "Manchester",
    region: "Greater Manchester",
    postcodes: "M1, M2, M3, M4, M5, M6, M7, M8, M9, M11, M12, M13, M14, M15, M16",
    areas: "Salford, Stockport, Trafford, Oldham, Rochdale, Bolton, Bury, Wigan, Tameside",
    description: "Affordable car recovery in Manchester & Greater Manchester. Fast 24/7 breakdown cover across all Manchester postcodes and surrounding boroughs.",
    intro: "Manchester's busy road network — from the M60 orbital to the city centre Mancunian Way — means breakdowns happen at the most inconvenient times. Our Manchester recovery team covers the entire Greater Manchester area, including Salford, Stockport, Trafford, and all surrounding boroughs. Fixed prices and instant online quotes mean no nasty surprises.",
    whyUs: "We have recovery agents spread across Greater Manchester so you're never waiting long. From the Northern Quarter to the Trafford Centre, Oldham to Wigan, our network ensures rapid response times across the region. We handle everything from flat tyres to full vehicle tows, 24 hours a day, 7 days a week.",
    faq1Q: "How quickly can you reach me in Manchester?",
    faq1A: "Response times vary by exact location and time of day, but our Manchester agents aim to reach you as quickly as possible. Our network covers the full M60 ring and beyond, so help is always close by.",
    faq2Q: "Do you cover breakdown recovery on the M60 and M62?",
    faq2A: "Absolutely. We provide recovery assistance on all major Manchester motorways including the M60, M62, M56, M61 and M63. Stay safe, hazard lights on, and we'll get to you.",
  },
  {
    slug: "london",
    name: "London",
    region: "Greater London",
    postcodes: "E, EC, N, NW, SE, SW, W, WC",
    areas: "North London, South London, East London, West London, Central London, Croydon, Greenwich, Barnet, Ealing",
    description: "Cheap car recovery in London. 24/7 breakdown and towing service across all London boroughs. Instant quotes, fixed pricing, fast response.",
    intro: "A breakdown in London is uniquely frustrating — from congested North Circular traffic to narrow South London streets. Our London recovery agents are spread across all 33 boroughs, providing fast car recovery whether you're stuck on the A406, the M25, or a back street in Greenwich. We serve all London postcodes with transparent fixed pricing.",
    whyUs: "London's complex road network requires experienced local agents. Our team covers every London borough — from Barnet in the north to Croydon in the south, Ealing in the west to Havering in the east. We understand the ULEZ zones, congestion charge areas, and the fastest routes to reach you quickly anywhere in the capital.",
    faq1Q: "Can you recover my car within the ULEZ zone in London?",
    faq1A: "Yes, our vehicles are ULEZ compliant and can recover your car from anywhere within the Ultra Low Emission Zone and Congestion Charge area in central London.",
    faq2Q: "Do you cover the M25 around London?",
    faq2A: "Yes, we provide breakdown recovery on the M25 and all major routes into and around London. If you've broken down on the motorway, stay safe in your vehicle with hazard lights on and contact us.",
  },
  {
    slug: "leeds",
    name: "Leeds",
    region: "West Yorkshire",
    postcodes: "LS1, LS2, LS3, LS4, LS5, LS6, LS7, LS8, LS9, LS10, LS11, LS12, LS13, LS14, LS15",
    areas: "Headingley, Beeston, Morley, Pudsey, Wetherby, Garforth, Otley, Horsforth, Roundhay",
    description: "Cheap car recovery in Leeds & West Yorkshire. 24/7 breakdown cover across Leeds and surrounding areas. Fast response, fixed prices.",
    intro: "Whether you've broken down on the M1, the A1(M), or in Leeds city centre, our local recovery agents know West Yorkshire roads inside out. We cover all Leeds postcodes and extend into surrounding West Yorkshire towns. Our fixed-price quotes mean you always know the cost before we arrive.",
    whyUs: "Our Leeds recovery network spans the entire city and wider West Yorkshire area — from Headingley and Roundhay to Morley and Garforth. We're familiar with the Leeds Inner Ring Road, the M62 corridor, and all the routes in between. Fast response, professional service, and no hidden costs.",
    faq1Q: "Do you provide car recovery on the M1 near Leeds?",
    faq1A: "Yes, we cover the M1, M62, A1(M) and all motorways and A-roads around Leeds. Motorway breakdowns are treated as priority and we aim to reach you as quickly as possible.",
    faq2Q: "Can you recover vans as well as cars in Leeds?",
    faq2A: "Yes, our Leeds agents recover cars, vans, and 4x4s. During the quote process, enter your vehicle registration so we can confirm the right vehicle weight class and send the appropriate recovery truck.",
  },
  {
    slug: "sheffield",
    name: "Sheffield",
    region: "South Yorkshire",
    postcodes: "S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S17",
    areas: "Hillsborough, Totley, Attercliffe, Woodseats, Dore, Chapeltown, Mosborough, Beighton",
    description: "Cheap car recovery in Sheffield & South Yorkshire. 24/7 breakdown and recovery service across all Sheffield postcodes.",
    intro: "Sheffield's hilly terrain and busy routes including the M1 and A57 present unique challenges when your car breaks down. Our South Yorkshire recovery agents are stationed across Sheffield to provide fast, affordable recovery regardless of where you've stopped. From Hillsborough to Dore, and everywhere between, we've got you covered.",
    whyUs: "Sheffield's unique geography means not every recovery company can navigate all areas efficiently. Our local agents know every Sheffield road — the steep hills of the south-west suburbs and the flatter east side alike. We cover all Sheffield postcodes and extend into Rotherham, Barnsley, and the wider South Yorkshire region.",
    faq1Q: "Do you cover the Peak District roads near Sheffield?",
    faq1A: "We cover the A57 Snake Pass and surrounding routes. For very remote Peak District locations, please mention this when getting your quote so we can ensure the right vehicle is dispatched.",
    faq2Q: "How do I get a quote for car recovery in Sheffield?",
    faq2A: "Use the instant quote form at the top of this page. Enter your collection address and destination, select your recovery type, add your vehicle reg and phone number, and we'll send your fixed-price quote by SMS.",
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    region: "Merseyside",
    postcodes: "L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12, L13, L14, L15",
    areas: "Bootle, Crosby, Huyton, Prescot, Speke, Halewood, Kirkby, Formby, Southport",
    description: "Cheap car recovery in Liverpool & Merseyside. 24/7 breakdown recovery across all Liverpool postcodes and Wirral.",
    intro: "From the Queensway Tunnel to the M57 and everything in between, a breakdown in Liverpool needs a fast local response. Our Merseyside recovery agents cover the full Liverpool postcode area and extend into the Wirral, Knowsley, Halton, and St Helens. Clear pricing and 24/7 availability mean you're never left stranded for long.",
    whyUs: "Our Liverpool recovery network covers both sides of the Mersey — including Wirral areas like Birkenhead and Wallasey. We handle everything from city centre breakdowns to motorway incidents on the M57 and M62, with agents positioned to give you a rapid response anywhere across Merseyside.",
    faq1Q: "Do you recover cars on the Wirral and across the Mersey?",
    faq1A: "Yes, we cover the Wirral peninsula including Birkenhead, Wallasey, Heswall and surrounding areas, as well as all Liverpool postcodes on the east bank of the Mersey.",
    faq2Q: "Can you recover a car from the Queensway or Kingsway Tunnel?",
    faq2A: "Tunnel breakdowns are handled by the tunnel authority as a first step. Once your vehicle is clear of the tunnel, our agents can take over recovery to your chosen destination.",
  },
  {
    slug: "bristol",
    name: "Bristol",
    region: "South West England",
    postcodes: "BS1, BS2, BS3, BS4, BS5, BS6, BS7, BS8, BS9, BS10, BS11, BS13, BS14, BS15, BS16",
    areas: "Clifton, Bedminster, Filton, Kingswood, Patchway, Thornbury, Nailsea, Portishead, Bath Road corridor",
    description: "Cheap car recovery in Bristol & South West. 24/7 breakdown and towing service across all Bristol postcodes and surrounding areas.",
    intro: "Bristol's mix of motorways, narrow Georgian streets, and the busy A4 corridor creates a challenging environment when your car breaks down. Our Bristol recovery agents cover the full BS postcode range and extend into North Somerset, South Gloucestershire, and Bath. Whether you're on the M32, the M5, or in Clifton, we provide fast, affordable recovery.",
    whyUs: "We know Bristol's unique road challenges — from the Clifton suspension bridge approach to the busy Cabot Circus area and the M32 spur. Our agents are stationed across the city and wider region to give you rapid cover whether you're in Kingswood, Bedminster, Filton, or anywhere else across the BS postcode area.",
    faq1Q: "Do you cover the M5 and M4 near Bristol?",
    faq1A: "Yes, we provide recovery on the M5, M4, M32 and all major routes in and around Bristol. Motorway recovery is handled as a priority call.",
    faq2Q: "Can you tow my car to a garage in Bristol?",
    faq2A: "Absolutely. We can transport your vehicle to any garage, home address, or repair facility across Bristol and the surrounding areas. Just enter your preferred destination in the quote form.",
  },
  {
    slug: "glasgow",
    name: "Glasgow",
    region: "Greater Glasgow & Clyde Valley",
    postcodes: "G1, G2, G3, G4, G5, G11, G12, G13, G14, G15, G20, G21, G22, G31, G32, G33",
    areas: "Govan, Partick, Maryhill, Shettleston, Rutherglen, Cambuslang, Bearsden, Milngavie, Paisley",
    description: "Cheap car recovery in Glasgow & Clyde Valley. 24/7 breakdown recovery across all Glasgow postcodes and surrounding areas in Scotland.",
    intro: "Glasgow's busy M8 motorway, the Kingston Bridge, and the wider Greater Glasgow road network are among Scotland's most congested routes. When your car breaks down, our Glasgow recovery agents respond quickly across all Glasgow postcodes and extend into Renfrewshire, East Dunbartonshire, and the wider Clyde Valley. Scottish drivers get the same fixed pricing and 24/7 service as anywhere else in our network.",
    whyUs: "Our Glasgow agents cover the full city — from the south side of Rutherglen and Cambuslang to the west end of Partick and Bearsden. We're on call around the clock to cover the M8, M74, M77, and all major Glasgow routes. Professional, insured, and local — we get you moving again fast.",
    faq1Q: "Do you cover car recovery on the M8 and M74 in Glasgow?",
    faq1A: "Yes, our Glasgow agents cover all Scottish motorways in the region including the M8, M74, M77, M73 and A74(M). Motorway breakdowns are treated as high priority.",
    faq2Q: "Are your Glasgow recovery prices the same as England?",
    faq2A: "Yes, our pricing is consistent across the UK including Scotland. Use the instant quote form to get your exact fixed price before we arrive.",
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    region: "City of Edinburgh & Lothian",
    postcodes: "EH1, EH2, EH3, EH4, EH5, EH6, EH7, EH8, EH9, EH10, EH11, EH12, EH13, EH14, EH15",
    areas: "Leith, Portobello, Morningside, Corstorphine, Musselburgh, Dalkeith, Livingston, Kirkcaldy approach",
    description: "Cheap car recovery in Edinburgh & Lothian. 24/7 breakdown recovery across Edinburgh and the wider Lothians region.",
    intro: "Edinburgh's historic streets, the busy City Bypass (A720), and the approaches to the Forth Road Bridge all present common breakdown scenarios. Our Edinburgh recovery agents cover all EH postcodes and extend into the Lothians, Fife (via the Forth Bridge), and the Scottish Borders. Fast response, transparent pricing, and professional service across the Scottish capital.",
    whyUs: "From the Old Town cobblestones to the Gyle Shopping Centre approach and the M8 connection to Glasgow, our Edinburgh agents know the local road network well. We cover Leith, Morningside, Corstorphine, Portobello and all Edinburgh areas with the same commitment to speed and value.",
    faq1Q: "Can you recover my car on the Edinburgh City Bypass (A720)?",
    faq1A: "Yes, we cover the A720, M8, M9 and all major routes in and around Edinburgh. If you're on a busy road, put your hazard lights on and stay safe while we head to you.",
    faq2Q: "Do you cover recovery across the Forth Bridge to Fife?",
    faq2A: "Yes, we can recover vehicles crossing or near the Queensferry Crossing and Forth Road Bridge area, and extend coverage into parts of Fife. Mention this in your quote request.",
  },
  {
    slug: "coventry",
    name: "Coventry",
    region: "West Midlands",
    postcodes: "CV1, CV2, CV3, CV4, CV5, CV6, CV7, CV8",
    areas: "Tile Hill, Canley, Longford, Binley, Cheylesmore, Earlsdon, Allesley, Kenilworth, Rugby",
    description: "Cheap car recovery in Coventry & Warwickshire. 24/7 breakdown and towing service across all Coventry postcodes.",
    intro: "Coventry sits at the heart of the UK motorway network — with the M6, M69, and A45 all converging nearby. Breakdowns here can happen on some of the country's busiest roads. Our Coventry recovery agents cover all CV postcodes and extend into Rugby, Kenilworth, and the wider Warwickshire area, providing fast, fixed-price recovery around the clock.",
    whyUs: "Our Coventry agents are strategically positioned to cover the full city and the surrounding motorway network. Whether you've stopped on the M6 near junction 2, the M69, or in Coventry city centre near the Cathedral, our team responds quickly with professional, fully insured recovery vehicles.",
    faq1Q: "Do you cover the M6 and M69 near Coventry?",
    faq1A: "Yes, we cover all Coventry motorways and A-roads including the M6 (junctions 2-3), M69, M45, and A45. Motorway recovery is our highest priority.",
    faq2Q: "How long does car recovery take in Coventry?",
    faq2A: "Response times depend on your exact location and time of day. Our agents across Coventry aim to reach you as fast as possible. Get an instant quote above and your SMS will include estimated timings.",
  },
  {
    slug: "leicester",
    name: "Leicester",
    region: "East Midlands",
    postcodes: "LE1, LE2, LE3, LE4, LE5, LE6, LE7, LE8, LE9",
    areas: "Oadby, Wigston, Hinckley, Loughborough, Market Harborough, Blaby, Birstall, Syston",
    description: "Cheap car recovery in Leicester & East Midlands. 24/7 breakdown cover across all Leicester postcodes and surrounding Leicestershire.",
    intro: "Leicester's road network — including the busy M1, M69, and A6 — makes it a common location for breakdowns. Our East Midlands recovery agents are stationed across the Leicester LE postcode area and into the wider Leicestershire county. From Oadby to Loughborough and Hinckley to Market Harborough, we provide fast, affordable recovery with fixed pricing.",
    whyUs: "Our Leicester network covers the entire city and county — including Oadby, Wigston, Loughborough and Hinckley. We're familiar with all local routes, including the A46 ring road and M1 junctions 20-23, ensuring our agents reach you quickly wherever you break down.",
    faq1Q: "Do you cover the M1 junctions near Leicester?",
    faq1A: "Yes, we cover M1 junctions 20 through 23A around Leicester, the M69 and all major A-roads in the area. Get your instant quote above for motorway recovery pricing.",
    faq2Q: "Can you tow my car to a specific garage in Leicester?",
    faq2A: "Yes, we deliver to any address in Leicester or the surrounding area — your preferred garage, home, or any other destination. Just enter it in the delivery address field on the quote form.",
  },
  {
    slug: "nottingham",
    name: "Nottingham",
    region: "East Midlands",
    postcodes: "NG1, NG2, NG3, NG4, NG5, NG6, NG7, NG8, NG9, NG10, NG11, NG12, NG13",
    areas: "Beeston, Arnold, Carlton, West Bridgford, Long Eaton, Hucknall, Ilkeston, Stapleford, Radcliffe on Trent",
    description: "Cheap car recovery in Nottingham & Nottinghamshire. 24/7 breakdown and towing service across all Nottingham postcodes.",
    intro: "From the M1 to the A52 and Nottingham's busy inner ring road, breakdowns can leave you stranded at the worst times. Our Nottinghamshire recovery agents cover the full NG postcode area — from the city centre to Beeston, Arnold, West Bridgford, and out to Long Eaton and Hucknall. Fixed pricing and 24/7 availability mean reliable help is always close.",
    whyUs: "Our Nottingham team covers the entire city and county. We handle everything from flat batteries in Arnold to full accident recovery on the M1 near junction 25. Local knowledge, professional equipment, and transparent fixed pricing are what set our Nottingham service apart.",
    faq1Q: "Do you cover M1 breakdowns near Nottingham?",
    faq1A: "Yes, we cover the M1 junctions 24-27 near Nottingham, the A52, A453, and all major roads in the area. Motorway incidents are our top priority.",
    faq2Q: "What types of vehicles do you recover in Nottingham?",
    faq2A: "We recover cars, vans, 4x4s and most light vehicles. Enter your vehicle registration in the quote form so we can confirm the vehicle class and send the right recovery truck.",
  },
  {
    slug: "newcastle",
    name: "Newcastle",
    region: "Tyne and Wear",
    postcodes: "NE1, NE2, NE3, NE4, NE5, NE6, NE7, NE8, NE9, NE10, NE11, NE12, NE13",
    areas: "Gateshead, Sunderland, Durham, Cramlington, Ponteland, Whickham, Blaydon, Hebburn, Jarrow",
    description: "Cheap car recovery in Newcastle & Tyne and Wear. 24/7 breakdown recovery across Newcastle, Gateshead, Sunderland and surrounding areas.",
    intro: "Newcastle upon Tyne and the wider Tyne and Wear region has a busy road network centred around the A1(M), A19, and A69. Our North East recovery agents cover all Newcastle NE postcodes, Gateshead, Sunderland, and extend south towards Durham and north into Northumberland. Professional, fast, and affordable recovery when you need it most.",
    whyUs: "We cover the full Tyne and Wear conurbation — from Newcastle city centre and Gateshead Quayside to Sunderland, South Tyneside, and North Tyneside. Our agents are familiar with the Tyne Bridge, A1(M), and A19 routes, ensuring quick response times across the entire region.",
    faq1Q: "Do you cover the A1(M) and A19 near Newcastle?",
    faq1A: "Yes, we provide recovery on the A1(M), A19, A69, A1 and all major routes around Newcastle and Tyne and Wear. Get your instant quote above.",
    faq2Q: "Can you recover my car across the Tyne to Gateshead?",
    faq2A: "Absolutely. We cover both sides of the Tyne — Newcastle and Gateshead — as well as Sunderland, Durham, and surrounding areas all under the same fixed-price service.",
  },
  {
    slug: "bradford",
    name: "Bradford",
    region: "West Yorkshire",
    postcodes: "BD1, BD2, BD3, BD4, BD5, BD6, BD7, BD8, BD9, BD10, BD11, BD12, BD13, BD14, BD15",
    areas: "Keighley, Shipley, Bingley, Ilkley, Otley, Guiseley, Cleckheaton, Heckmondwike, Pudsey",
    description: "Cheap car recovery in Bradford & West Yorkshire. 24/7 breakdown and towing service across all Bradford postcodes.",
    intro: "Bradford's position in the Aire Valley and its connections to the M606, M62, and surrounding West Yorkshire roads means breakdowns can happen on hilly, busy routes. Our recovery agents cover all Bradford BD postcodes and extend into Keighley, Bingley, Ilkley, and surrounding West Yorkshire towns. Fast response and fixed pricing — no surprises.",
    whyUs: "Our Bradford agents know the local roads — from the steep routes around the city centre to the M606 Bradford spur and M62 connections. We cover Shipley, Keighley, Ilkley, Bingley, Cleckheaton and all surrounding areas with the same professional recovery service.",
    faq1Q: "Do you cover the M606 Bradford Spur and M62?",
    faq1A: "Yes, our Bradford recovery agents cover the M606, M62, A650 and all major Bradford routes. Enter your motorway location in the quote form for accurate pricing.",
    faq2Q: "How do I pay for car recovery in Bradford?",
    faq2A: "You pay after the job is complete. Your fixed price is confirmed via SMS before we arrive so there are no surprises. Most agents accept card and cash payment.",
  },
  {
    slug: "cardiff",
    name: "Cardiff",
    region: "South Wales",
    postcodes: "CF10, CF11, CF14, CF15, CF23, CF24, CF3, CF5, CF62, CF63, CF64",
    areas: "Penarth, Barry, Pontypridd, Caerphilly, Newport, Bridgend, Vale of Glamorgan, Rhondda",
    description: "Cheap car recovery in Cardiff & South Wales. 24/7 breakdown recovery across Cardiff and the surrounding South Wales region.",
    intro: "Cardiff is South Wales's main hub, and its road network — including the M4, A470, and A48 — sees heavy daily traffic. Breakdowns on these routes need a fast local response. Our South Wales recovery agents cover all Cardiff CF postcodes and extend into Newport, Barry, Penarth, Pontypridd, and across the wider Vale of Glamorgan. Fixed prices, instant quotes, available 24/7.",
    whyUs: "We cover Cardiff city centre, the Bay area, north Cardiff suburbs, and the wider South Wales region. Our agents are familiar with M4 junctions, the A470 Heads of the Valleys approach, and all routes into and around the Welsh capital. The same professional, affordable service you'd expect anywhere in the UK.",
    faq1Q: "Do you cover the M4 motorway in South Wales?",
    faq1A: "Yes, we cover the M4 across South Wales including junctions around Cardiff, Newport, and Bridgend. Motorway recovery is always our top priority.",
    faq2Q: "Can you recover a car from Cardiff to another Welsh city?",
    faq2A: "Yes, we offer A-to-B transportation anywhere in Wales and across the UK. Enter your destination in the Delivery Address field and your quote will reflect the full distance.",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}
