export type CityData = {
  slug: string;
  name: string;
  region: string;
  postcodes: string;
  areas: string;
  description: string;
  intro: string;
  whyUs: string;
  faq1Q: string;
  faq1A: string;
  faq2Q: string;
  faq2A: string;
};

export const cities: CityData[] = [
  {
    slug: "birmingham",
    name: "Birmingham",
    region: "West Midlands",
    postcodes: "B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, B15",
    areas: "Solihull, Sutton Coldfield, Edgbaston, Erdington, Handsworth, Moseley, Kings Heath, Selly Oak",
    description: "Cheap car recovery in Birmingham & West Midlands. 24/7 breakdown assistance, towing, and roadside help across all Birmingham postcodes.",
    intro: "Breaking down in Birmingham can be stressful — from the busy M6 corridor to the city centre ring road. Our Birmingham recovery agents are positioned across the West Midlands to reach you fast, whether you're stuck on the A38, the M5, or a quiet suburban street in Edgbaston. We cover every Birmingham postcode with no hidden fees and fixed pricing.",
    whyUs: "With multiple recovery vehicles stationed across Birmingham and the wider West Midlands, we consistently achieve some of the fastest response times in the region. Our agents cover Solihull, Sutton Coldfield, Erdington, Moseley, Selly Oak, Handsworth and everywhere in between — so wherever your car lets you down in Birmingham, help is never far away.",
    faq1Q: "How much does car recovery cost in Birmingham?",
    faq1A: "Our Birmingham car recovery quotes start from a fixed price based on distance and vehicle type. Use our instant quote form above to get your exact price before you commit — no surprises, no call-out fees.",
    faq2Q: "Do you cover motorways near Birmingham?",
    faq2A: "Yes. We assist on the M6, M5, M42, and A38(M) — all major routes in and around Birmingham. If you've broken down on a motorway, stay in your vehicle with hazard lights on and call us immediately.",
  },
  {
    slug: "manchester",
    name: "Manchester",
    region: "Greater Manchester",
    postcodes: "M1, M2, M3, M4, M5, M6, M7, M8, M9, M11, M12, M13, M14, M15, M16",
    areas: "Salford, Stockport, Trafford, Oldham, Rochdale, Bolton, Bury, Wigan, Tameside",
    description: "Affordable car recovery in Manchester & Greater Manchester. Fast 24/7 breakdown cover across all Manchester postcodes and surrounding boroughs.",
    intro: "Manchester's busy road network — from the M60 orbital to the city centre Mancunian Way — means breakdowns happen at the most inconvenient times. Our Manchester recovery team covers the entire Greater Manchester area, including Salford, Stockport, Trafford, and all surrounding boroughs. Fixed prices and instant online quotes mean no nasty surprises.",
    whyUs: "We have recovery agents spread across Greater Manchester so you're never waiting long. From the Northern Quarter to the Trafford Centre, Oldham to Wigan, our network ensures rapid response times across the region. We handle everything from flat tyres to full vehicle tows, 24 hours a day, 7 days a week.",
    faq1Q: "How quickly can you reach me in Manchester?",
    faq1A: "Response times vary by exact location and time of day, but our Manchester agents aim to reach you as quickly as possible. Our network covers the full M60 ring and beyond, so help is always close by.",
    faq2Q: "Do you cover breakdown recovery on the M60 and M62?",
    faq2A: "Absolutely. We provide recovery assistance on all major Manchester motorways including the M60, M62, M56, M61 and M63. Stay safe, hazard lights on, and we'll get to you.",
  },
  {
    slug: "london",
    name: "London",
    region: "Greater London",
    postcodes: "E, EC, N, NW, SE, SW, W, WC",
    areas: "North London, South London, East London, West London, Central London, Croydon, Greenwich, Barnet, Ealing",
    description: "Cheap car recovery in London. 24/7 breakdown and towing service across all London boroughs. Instant quotes, fixed pricing, fast response.",
    intro: "A breakdown in London is uniquely frustrating — from congested North Circular traffic to narrow South London streets. Our London recovery agents are spread across all 33 boroughs, providing fast car recovery whether you're stuck on the A406, the M25, or a back street in Greenwich. We serve all London postcodes with transparent fixed pricing.",
    whyUs: "London's complex road network requires experienced local agents. Our team covers every London borough — from Barnet in the north to Croydon in the south, Ealing in the west to Havering in the east. We understand the ULEZ zones, congestion charge areas, and the fastest routes to reach you quickly anywhere in the capital.",
    faq1Q: "Can you recover my car within the ULEZ zone in London?",
    faq1A: "Yes, our vehicles are ULEZ compliant and can recover your car from anywhere within the Ultra Low Emission Zone and Congestion Charge area in central London.",
    faq2Q: "Do you cover the M25 around London?",
    faq2A: "Yes, we provide breakdown recovery on the M25 and all major routes into and around London. If you've broken down on the motorway, stay safe in your vehicle with hazard lights on and contact us.",
  },
  {
    slug: "leeds",
    name: "Leeds",
    region: "West Yorkshire",
    postcodes: "LS1, LS2, LS3, LS4, LS5, LS6, LS7, LS8, LS9, LS10, LS11, LS12, LS13, LS14, LS15",
    areas: "Headingley, Beeston, Morley, Pudsey, Wetherby, Garforth, Otley, Horsforth, Roundhay",
    description: "Cheap car recovery in Leeds & West Yorkshire. 24/7 breakdown cover across Leeds and surrounding areas. Fast response, fixed prices.",
    intro: "Whether you've broken down on the M1, the A1(M), or in Leeds city centre, our local recovery agents know West Yorkshire roads inside out. We cover all Leeds postcodes and extend into surrounding West Yorkshire towns. Our fixed-price quotes mean you always know the cost before we arrive.",
    whyUs: "Our Leeds recovery network spans the entire city and wider West Yorkshire area — from Headingley and Roundhay to Morley and Garforth. We're familiar with the Leeds Inner Ring Road, the M62 corridor, and all the routes in between. Fast response, professional service, and no hidden costs.",
    faq1Q: "Do you provide car recovery on the M1 near Leeds?",
    faq1A: "Yes, we cover the M1, M62, A1(M) and all motorways and A-roads around Leeds. Motorway breakdowns are treated as priority and we aim to reach you as quickly as possible.",
    faq2Q: "Can you recover vans as well as cars in Leeds?",
    faq2A: "Yes, our Leeds agents recover cars, vans, and 4x4s. During the quote process, enter your vehicle registration so we can confirm the right vehicle weight class and send the appropriate recovery truck.",
  },
  {
    slug: "sheffield",
    name: "Sheffield",
    region: "South Yorkshire",
    postcodes: "S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S17",
    areas: "Hillsborough, Totley, Attercliffe, Woodseats, Dore, Chapeltown, Mosborough, Beighton",
    description: "Cheap car recovery in Sheffield & South Yorkshire. 24/7 breakdown and recovery service across all Sheffield postcodes.",
    intro: "Sheffield's hilly terrain and busy routes including the M1 and A57 present unique challenges when your car breaks down. Our South Yorkshire recovery agents are stationed across Sheffield to provide fast, affordable recovery regardless of where you've stopped. From Hillsborough to Dore, and everywhere between, we've got you covered.",
    whyUs: "Sheffield's unique geography means not every recovery company can navigate all areas efficiently. Our local agents know every Sheffield road — the steep hills of the south-west suburbs and the flatter east side alike. We cover all Sheffield postcodes and extend into Rotherham, Barnsley, and the wider South Yorkshire region.",
    faq1Q: "Do you cover the Peak District roads near Sheffield?",
    faq1A: "We cover the A57 Snake Pass and surrounding routes. For very remote Peak District locations, please mention this when getting your quote so we can ensure the right vehicle is dispatched.",
    faq2Q: "How do I get a quote for car recovery in Sheffield?",
    faq2A: "Use the instant quote form at the top of this page. Enter your collection address and destination, select your recovery type, add your vehicle reg and phone number, and we'll send your fixed-price quote by SMS.",
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    region: "Merseyside",
    postcodes: "L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12, L13, L14, L15",
    areas: "Bootle, Crosby, Huyton, Prescot, Speke, Halewood, Kirkby, Formby, Southport",
    description: "Cheap car recovery in Liverpool & Merseyside. 24/7 breakdown recovery across all Liverpool postcodes and Wirral.",
    intro: "From the Queensway Tunnel to the M57 and everything in between, a breakdown in Liverpool needs a fast local response. Our Merseyside recovery agents cover the full Liverpool postcode area and extend into the Wirral, Knowsley, Halton, and St Helens. Clear pricing and 24/7 availability mean you're never left stranded for long.",
    whyUs: "Our Liverpool recovery network covers both sides of the Mersey — including Wirral areas like Birkenhead and Wallasey. We handle everything from city centre breakdowns to motorway incidents on the M57 and M62, with agents positioned to give you a rapid response anywhere across Merseyside.",
    faq1Q: "Do you recover cars on the Wirral and across the Mersey?",
    faq1A: "Yes, we cover the Wirral peninsula including Birkenhead, Wallasey, Heswall and surrounding areas, as well as all Liverpool postcodes on the east bank of the Mersey.",
    faq2Q: "Can you recover a car from the Queensway or Kingsway Tunnel?",
    faq2A: "Tunnel breakdowns are handled by the tunnel authority as a first step. Once your vehicle is clear of the tunnel, our agents can take over recovery to your chosen destination.",
  },
  {
    slug: "bristol",
    name: "Bristol",
    region: "South West England",
    postcodes: "BS1, BS2, BS3, BS4, BS5, BS6, BS7, BS8, BS9, BS10, BS11, BS13, BS14, BS15, BS16",
    areas: "Clifton, Bedminster, Filton, Kingswood, Patchway, Thornbury, Nailsea, Portishead, Bath Road corridor",
    description: "Cheap car recovery in Bristol & South West. 24/7 breakdown and towing service across all Bristol postcodes and surrounding areas.",
    intro: "Bristol's mix of motorways, narrow Georgian streets, and the busy A4 corridor creates a challenging environment when your car breaks down. Our Bristol recovery agents cover the full BS postcode range and extend into North Somerset, South Gloucestershire, and Bath. Whether you're on the M32, the M5, or in Clifton, we provide fast, affordable recovery.",
    whyUs: "We know Bristol's unique road challenges — from the Clifton suspension bridge approach to the busy Cabot Circus area and the M32 spur. Our agents are stationed across the city and wider region to give you rapid cover whether you're in Kingswood, Bedminster, Filton, or anywhere else across the BS postcode area.",
    faq1Q: "Do you cover the M5 and M4 near Bristol?",
    faq1A: "Yes, we provide recovery on the M5, M4, M32 and all major routes in and around Bristol. Motorway recovery is handled as a priority call.",
    faq2Q: "Can you tow my car to a garage in Bristol?",
    faq2A: "Absolutely. We can transport your vehicle to any garage, home address, or repair facility across Bristol and the surrounding areas. Just enter your preferred destination in the quote form.",
  },
  {
    slug: "glasgow",
    name: "Glasgow",
    region: "Greater Glasgow & Clyde Valley",
    postcodes: "G1, G2, G3, G4, G5, G11, G12, G13, G14, G15, G20, G21, G22, G31, G32, G33",
    areas: "Govan, Partick, Maryhill, Shettleston, Rutherglen, Cambuslang, Bearsden, Milngavie, Paisley",
    description: "Cheap car recovery in Glasgow & Clyde Valley. 24/7 breakdown recovery across all Glasgow postcodes and surrounding areas in Scotland.",
    intro: "Glasgow's busy M8 motorway, the Kingston Bridge, and the wider Greater Glasgow road network are among Scotland's most congested routes. When your car breaks down, our Glasgow recovery agents respond quickly across all Glasgow postcodes and extend into Renfrewshire, East Dunbartonshire, and the wider Clyde Valley. Scottish drivers get the same fixed pricing and 24/7 service as anywhere else in our network.",
    whyUs: "Our Glasgow agents cover the full city — from the south side of Rutherglen and Cambuslang to the west end of Partick and Bearsden. We're on call around the clock to cover the M8, M74, M77, and all major Glasgow routes. Professional, insured, and local — we get you moving again fast.",
    faq1Q: "Do you cover car recovery on the M8 and M74 in Glasgow?",
    faq1A: "Yes, our Glasgow agents cover all Scottish motorways in the region including the M8, M74, M77, M73 and A74(M). Motorway breakdowns are treated as high priority.",
    faq2Q: "Are your Glasgow recovery prices the same as England?",
    faq2A: "Yes, our pricing is consistent across the UK including Scotland. Use the instant quote form to get your exact fixed price before we arrive.",
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    region: "City of Edinburgh & Lothian",
    postcodes: "EH1, EH2, EH3, EH4, EH5, EH6, EH7, EH8, EH9, EH10, EH11, EH12, EH13, EH14, EH15",
    areas: "Leith, Portobello, Morningside, Corstorphine, Musselburgh, Dalkeith, Livingston, Kirkcaldy approach",
    description: "Cheap car recovery in Edinburgh & Lothian. 24/7 breakdown recovery across Edinburgh and the wider Lothians region.",
    intro: "Edinburgh's historic streets, the busy City Bypass (A720), and the approaches to the Forth Road Bridge all present common breakdown scenarios. Our Edinburgh recovery agents cover all EH postcodes and extend into the Lothians, Fife (via the Forth Bridge), and the Scottish Borders. Fast response, transparent pricing, and professional service across the Scottish capital.",
    whyUs: "From the Old Town cobblestones to the Gyle Shopping Centre approach and the M8 connection to Glasgow, our Edinburgh agents know the local road network well. We cover Leith, Morningside, Corstorphine, Portobello and all Edinburgh areas with the same commitment to speed and value.",
    faq1Q: "Can you recover my car on the Edinburgh City Bypass (A720)?",
    faq1A: "Yes, we cover the A720, M8, M9 and all major routes in and around Edinburgh. If you're on a busy road, put your hazard lights on and stay safe while we head to you.",
    faq2Q: "Do you cover recovery across the Forth Bridge to Fife?",
    faq2A: "Yes, we can recover vehicles crossing or near the Queensferry Crossing and Forth Road Bridge area, and extend coverage into parts of Fife. Mention this in your quote request.",
  },
  {
    slug: "coventry",
    name: "Coventry",
    region: "West Midlands",
    postcodes: "CV1, CV2, CV3, CV4, CV5, CV6, CV7, CV8",
    areas: "Tile Hill, Canley, Longford, Binley, Cheylesmore, Earlsdon, Allesley, Kenilworth, Rugby",
    description: "Cheap car recovery in Coventry & Warwickshire. 24/7 breakdown and towing service across all Coventry postcodes.",
    intro: "Coventry sits at the heart of the UK motorway network — with the M6, M69, and A45 all converging nearby. Breakdowns here can happen on some of the country's busiest roads. Our Coventry recovery agents cover all CV postcodes and extend into Rugby, Kenilworth, and the wider Warwickshire area, providing fast, fixed-price recovery around the clock.",
    whyUs: "Our Coventry agents are strategically positioned to cover the full city and the surrounding motorway network. Whether you've stopped on the M6 near junction 2, the M69, or in Coventry city centre near the Cathedral, our team responds quickly with professional, fully insured recovery vehicles.",
    faq1Q: "Do you cover the M6 and M69 near Coventry?",
    faq1A: "Yes, we cover all Coventry motorways and A-roads including the M6 (junctions 2-3), M69, M45, and A45. Motorway recovery is our highest priority.",
    faq2Q: "How long does car recovery take in Coventry?",
    faq2A: "Response times depend on your exact location and time of day. Our agents across Coventry aim to reach you as fast as possible. Get an instant quote above and your SMS will include estimated timings.",
  },
  {
    slug: "leicester",
    name: "Leicester",
    region: "East Midlands",
    postcodes: "LE1, LE2, LE3, LE4, LE5, LE6, LE7, LE8, LE9",
    areas: "Oadby, Wigston, Hinckley, Loughborough, Market Harborough, Blaby, Birstall, Syston",
    description: "Cheap car recovery in Leicester & East Midlands. 24/7 breakdown cover across all Leicester postcodes and surrounding Leicestershire.",
    intro: "Leicester's road network — including the busy M1, M69, and A6 — makes it a common location for breakdowns. Our East Midlands recovery agents are stationed across the Leicester LE postcode area and into the wider Leicestershire county. From Oadby to Loughborough and Hinckley to Market Harborough, we provide fast, affordable recovery with fixed pricing.",
    whyUs: "Our Leicester network covers the entire city and county — including Oadby, Wigston, Loughborough and Hinckley. We're familiar with all local routes, including the A46 ring road and M1 junctions 20-23, ensuring our agents reach you quickly wherever you break down.",
    faq1Q: "Do you cover the M1 junctions near Leicester?",
    faq1A: "Yes, we cover M1 junctions 20 through 23A around Leicester, the M69 and all major A-roads in the area. Get your instant quote above for motorway recovery pricing.",
    faq2Q: "Can you tow my car to a specific garage in Leicester?",
    faq2A: "Yes, we deliver to any address in Leicester or the surrounding area — your preferred garage, home, or any other destination. Just enter it in the delivery address field on the quote form.",
  },
  {
    slug: "nottingham",
    name: "Nottingham",
    region: "East Midlands",
    postcodes: "NG1, NG2, NG3, NG4, NG5, NG6, NG7, NG8, NG9, NG10, NG11, NG12, NG13",
    areas: "Beeston, Arnold, Carlton, West Bridgford, Long Eaton, Hucknall, Ilkeston, Stapleford, Radcliffe on Trent",
    description: "Cheap car recovery in Nottingham & Nottinghamshire. 24/7 breakdown and towing service across all Nottingham postcodes.",
    intro: "From the M1 to the A52 and Nottingham's busy inner ring road, breakdowns can leave you stranded at the worst times. Our Nottinghamshire recovery agents cover the full NG postcode area — from the city centre to Beeston, Arnold, West Bridgford, and out to Long Eaton and Hucknall. Fixed pricing and 24/7 availability mean reliable help is always close.",
    whyUs: "Our Nottingham team covers the entire city and county. We handle everything from flat batteries in Arnold to full accident recovery on the M1 near junction 25. Local knowledge, professional equipment, and transparent fixed pricing are what set our Nottingham service apart.",
    faq1Q: "Do you cover M1 breakdowns near Nottingham?",
    faq1A: "Yes, we cover the M1 junctions 24-27 near Nottingham, the A52, A453, and all major roads in the area. Motorway incidents are our top priority.",
    faq2Q: "What types of vehicles do you recover in Nottingham?",
    faq2A: "We recover cars, vans, 4x4s and most light vehicles. Enter your vehicle registration in the quote form so we can confirm the vehicle class and send the right recovery truck.",
  },
  {
    slug: "newcastle",
    name: "Newcastle",
    region: "Tyne and Wear",
    postcodes: "NE1, NE2, NE3, NE4, NE5, NE6, NE7, NE8, NE9, NE10, NE11, NE12, NE13",
    areas: "Gateshead, Sunderland, Durham, Cramlington, Ponteland, Whickham, Blaydon, Hebburn, Jarrow",
    description: "Cheap car recovery in Newcastle & Tyne and Wear. 24/7 breakdown recovery across Newcastle, Gateshead, Sunderland and surrounding areas.",
    intro: "Newcastle upon Tyne and the wider Tyne and Wear region has a busy road network centred around the A1(M), A19, and A69. Our North East recovery agents cover all Newcastle NE postcodes, Gateshead, Sunderland, and extend south towards Durham and north into Northumberland. Professional, fast, and affordable recovery when you need it most.",
    whyUs: "We cover the full Tyne and Wear conurbation — from Newcastle city centre and Gateshead Quayside to Sunderland, South Tyneside, and North Tyneside. Our agents are familiar with the Tyne Bridge, A1(M), and A19 routes, ensuring quick response times across the entire region.",
    faq1Q: "Do you cover the A1(M) and A19 near Newcastle?",
    faq1A: "Yes, we provide recovery on the A1(M), A19, A69, A1 and all major routes around Newcastle and Tyne and Wear. Get your instant quote above.",
    faq2Q: "Can you recover my car across the Tyne to Gateshead?",
    faq2A: "Absolutely. We cover both sides of the Tyne — Newcastle and Gateshead — as well as Sunderland, Durham, and surrounding areas all under the same fixed-price service.",
  },
  {
    slug: "bradford",
    name: "Bradford",
    region: "West Yorkshire",
    postcodes: "BD1, BD2, BD3, BD4, BD5, BD6, BD7, BD8, BD9, BD10, BD11, BD12, BD13, BD14, BD15",
    areas: "Keighley, Shipley, Bingley, Ilkley, Otley, Guiseley, Cleckheaton, Heckmondwike, Pudsey",
    description: "Cheap car recovery in Bradford & West Yorkshire. 24/7 breakdown and towing service across all Bradford postcodes.",
    intro: "Bradford's position in the Aire Valley and its connections to the M606, M62, and surrounding West Yorkshire roads means breakdowns can happen on hilly, busy routes. Our recovery agents cover all Bradford BD postcodes and extend into Keighley, Bingley, Ilkley, and surrounding West Yorkshire towns. Fast response and fixed pricing — no surprises.",
    whyUs: "Our Bradford agents know the local roads — from the steep routes around the city centre to the M606 Bradford spur and M62 connections. We cover Shipley, Keighley, Ilkley, Bingley, Cleckheaton and all surrounding areas with the same professional recovery service.",
    faq1Q: "Do you cover the M606 Bradford Spur and M62?",
    faq1A: "Yes, our Bradford recovery agents cover the M606, M62, A650 and all major Bradford routes. Enter your motorway location in the quote form for accurate pricing.",
    faq2Q: "How do I pay for car recovery in Bradford?",
    faq2A: "You pay after the job is complete. Your fixed price is confirmed via SMS before we arrive so there are no surprises. Most agents accept card and cash payment.",
  },
  {
    slug: "cardiff",
    name: "Cardiff",
    region: "South Wales",
    postcodes: "CF10, CF11, CF14, CF15, CF23, CF24, CF3, CF5, CF62, CF63, CF64",
    areas: "Penarth, Barry, Pontypridd, Caerphilly, Newport, Bridgend, Vale of Glamorgan, Rhondda",
    description: "Cheap car recovery in Cardiff & South Wales. 24/7 breakdown recovery across Cardiff and the surrounding South Wales region.",
    intro: "Cardiff is South Wales's main hub, and its road network — including the M4, A470, and A48 — sees heavy daily traffic. Breakdowns on these routes need a fast local response. Our South Wales recovery agents cover all Cardiff CF postcodes and extend into Newport, Barry, Penarth, Pontypridd, and across the wider Vale of Glamorgan. Fixed prices, instant quotes, available 24/7.",
    whyUs: "We cover Cardiff city centre, the Bay area, north Cardiff suburbs, and the wider South Wales region. Our agents are familiar with M4 junctions, the A470 Heads of the Valleys approach, and all routes into and around the Welsh capital. The same professional, affordable service you'd expect anywhere in the UK.",
    faq1Q: "Do you cover the M4 motorway in South Wales?",
    faq1A: "Yes, we cover the M4 across South Wales including junctions around Cardiff, Newport, and Bridgend. Motorway recovery is always our top priority.",
    faq2Q: "Can you recover a car from Cardiff to another Welsh city?",
    faq2A: "Yes, we offer A-to-B transportation anywhere in Wales and across the UK. Enter your destination in the Delivery Address field and your quote will reflect the full distance.",
  },
  {
    slug: "southampton",
    name: "Southampton",
    region: "Hampshire",
    postcodes: "SO14, SO15, SO16, SO17, SO18, SO19, SO40, SO45",
    areas: "Eastleigh, Romsey, Totton, Hedge End, Chandler's Ford, Hythe, Netley, Hamble",
    description: "Cheap car recovery in Southampton & Hampshire. 24/7 breakdown recovery across all Southampton postcodes and surrounding areas.",
    intro: "Southampton's busy M27, M3, and A3024 road network, plus the port approaches, mean breakdowns can happen in some of the UK's most congested spots. Our Hampshire recovery agents cover all Southampton SO postcodes and extend into Eastleigh, Romsey, Hedge End, and the New Forest. Fast, fixed-price recovery available around the clock.",
    whyUs: "Our Southampton agents know the port approach roads, the M27 junctions, and the city centre one-way system. We cover Totton, Hythe, Chandler's Ford and surrounding areas with professional recovery vehicles suitable for cars, vans, and 4x4s — all at transparent fixed prices.",
    faq1Q: "Do you cover the M27 and M3 near Southampton?",
    faq1A: "Yes, we cover the M27, M3, A3024 and all major routes around Southampton. Motorway and major road recovery is treated as a priority call.",
    faq2Q: "Can you recover a car near Southampton docks?",
    faq2A: "Yes, we cover the port area and surrounding roads. If you need recovery from a restricted docks area, please mention this when getting your quote so we can advise on access.",
  },
  {
    slug: "portsmouth",
    name: "Portsmouth",
    region: "Hampshire",
    postcodes: "PO1, PO2, PO3, PO4, PO5, PO6, PO7, PO8, PO9",
    areas: "Fareham, Gosport, Havant, Waterlooville, Chichester, Petersfield, Lee-on-Solent, Portchester",
    description: "Cheap car recovery in Portsmouth & Hampshire. 24/7 breakdown recovery across Portsea Island and surrounding areas.",
    intro: "Portsmouth's island geography and connections via the M27 and A3(M) create unique recovery challenges. Our agents cover all Portsmouth PO postcodes, the Gosport peninsula, Fareham, Havant, and Waterlooville. Fixed pricing means you know the cost before we arrive — no matter where on the island you break down.",
    whyUs: "Recovering a car on Portsea Island requires local knowledge — especially around the M275 port approaches and the tight streets of Old Portsmouth. Our local agents navigate these efficiently and extend their coverage to the mainland including Fareham, Gosport, and Chichester.",
    faq1Q: "Do you cover the M27 and A3(M) near Portsmouth?",
    faq1A: "Yes, we cover the M27, A3(M), M275 and all major routes into and around Portsmouth. Motorway incidents are treated as our highest priority.",
    faq2Q: "Can you recover a car on Portsea Island?",
    faq2A: "Yes, we cover all of Portsea Island including Portsmouth city centre, Southsea, Fratton, and North End. Just enter your collection address in the quote form.",
  },
  {
    slug: "plymouth",
    name: "Plymouth",
    region: "Devon",
    postcodes: "PL1, PL2, PL3, PL4, PL5, PL6, PL7, PL9",
    areas: "Devonport, Plympton, Plymstock, Saltash, Torpoint, Ivybridge, Newton Abbot approach, Liskeard",
    description: "Cheap car recovery in Plymouth & Devon. 24/7 breakdown recovery across all Plymouth postcodes and surrounding South West areas.",
    intro: "Plymouth is the gateway to Cornwall and the South West, with the A38 Devon Expressway as its main arterial route. Breakdowns here can leave you stranded far from the nearest garage. Our Devon recovery agents cover all Plymouth PL postcodes and extend across the Tamar into Cornwall. Professional, fixed-price recovery whenever you need it.",
    whyUs: "Our Plymouth agents are familiar with the A38, the Tamar crossings at Saltash, and the city's unique geography. We cover Devonport, Plympton, Plymstock, and extend into Ivybridge and surrounding rural Devon — ensuring fast response times even in areas where local recovery options are limited.",
    faq1Q: "Do you cover the A38 Devon Expressway near Plymouth?",
    faq1A: "Yes, we provide recovery on the A38 throughout Devon and into Cornwall. The A38 Devon Expressway is one of our most frequently served routes.",
    faq2Q: "Can you tow my car from Plymouth to Exeter or Cornwall?",
    faq2A: "Yes, we offer A-to-B transportation across the South West including to Exeter, Truro, and anywhere else in Cornwall or Devon. Enter your destination in the quote form for a fixed price.",
  },
  {
    slug: "derby",
    name: "Derby",
    region: "East Midlands",
    postcodes: "DE1, DE21, DE22, DE23, DE24, DE3, DE65, DE72, DE73, DE74",
    areas: "Ilkeston, Long Eaton, Burton upon Trent, Uttoxeter, Belper, Matlock approach, Swadlincote, Ashbourne",
    description: "Cheap car recovery in Derby & Derbyshire. 24/7 breakdown recovery across all Derby postcodes and surrounding East Midlands areas.",
    intro: "Derby sits at the heart of the East Midlands with the A50, A38, and M1 all nearby. As a major manufacturing centre, its roads carry heavy traffic at all hours. Our Derby recovery agents cover all Derby DE postcodes and extend into Ilkeston, Long Eaton, Burton upon Trent, and the surrounding Derbyshire countryside.",
    whyUs: "Our Derby agents cover the city and surrounding areas efficiently — from the busy Pride Park and A52 to the quieter villages of rural Derbyshire. We handle everything from city centre flat batteries to motorway incidents on the A50 and A38 corridors.",
    faq1Q: "Do you cover the A50 and A38 near Derby?",
    faq1A: "Yes, we cover the A50, A38, M1 (junctions 24-25) and all major routes around Derby. We prioritise recovery on major roads and dual carriageways.",
    faq2Q: "Do you recover cars near the Derby industrial and business parks?",
    faq2A: "Yes, we cover all Derby postcodes including the Pride Park and Sinfin Lane industrial areas. Enter your exact collection address in the quote form for an accurate fixed price.",
  },
  {
    slug: "wolverhampton",
    name: "Wolverhampton",
    region: "West Midlands",
    postcodes: "WV1, WV2, WV3, WV4, WV5, WV6, WV10, WV11, WV12, WV13, WV14",
    areas: "Bilston, Tipton, Wednesbury, Cannock, Perton, Tettenhall, Wednesfield, Willenhall, Walsall",
    description: "Cheap car recovery in Wolverhampton & Black Country. 24/7 breakdown recovery across all Wolverhampton postcodes.",
    intro: "Wolverhampton is at the centre of the Black Country road network, with the M54, M6, and M6 Toll all within easy reach. Breakdowns in this dense urban area need fast local response. Our West Midlands recovery agents cover all Wolverhampton WV postcodes and the wider Black Country — including Walsall, Bilston, Tipton, and Cannock.",
    whyUs: "We cover the entire Black Country conurbation from Wolverhampton city centre to the surrounding boroughs. Our agents are positioned across the WV postcode area and into Walsall and Cannock, giving rapid coverage across the M54 corridor and all local roads.",
    faq1Q: "Do you cover the M54 and M6 near Wolverhampton?",
    faq1A: "Yes, we cover the M54 (all junctions), M6 Toll, and M6 around Wolverhampton. Motorway recovery is our highest priority service.",
    faq2Q: "Do you recover cars in the Black Country area?",
    faq2A: "Yes, we cover the entire Black Country including Walsall, Dudley, Sandwell, and all surrounding areas within the WV postcode range.",
  },
  {
    slug: "swindon",
    name: "Swindon",
    region: "Wiltshire",
    postcodes: "SN1, SN2, SN3, SN4, SN5, SN6, SN25, SN26",
    areas: "Royal Wootton Bassett, Cricklade, Chippenham, Marlborough, Cirencester approach, Highworth, Wroughton",
    description: "Cheap car recovery in Swindon & Wiltshire. 24/7 breakdown recovery across all Swindon postcodes and surrounding Wiltshire areas.",
    intro: "Swindon sits at the intersection of the M4, A419, and A420 — making it one of the South West's major motorway junction towns. Breakdowns near these junctions are common, and our Wiltshire recovery agents cover all Swindon SN postcodes and extend into Chippenham, Marlborough, and Cirencester. Fast response, clear fixed pricing, 24/7.",
    whyUs: "Our Swindon agents are positioned to cover M4 junctions 15 and 16 rapidly, along with all local Swindon roads. We extend coverage into Royal Wootton Bassett, Highworth, and Cricklade — ensuring rural Wiltshire drivers are never left stranded far from help.",
    faq1Q: "Do you cover M4 junctions 15 and 16 near Swindon?",
    faq1A: "Yes, M4 junctions 15 and 16 near Swindon are regularly served routes for our recovery agents. All M4 motorway incidents are treated as priority calls.",
    faq2Q: "Can you recover a car from Swindon to another city?",
    faq2A: "Yes, we provide A-to-B transportation from Swindon to anywhere in the UK. Just enter your destination in the quote form to get your fixed price.",
  },
  {
    slug: "reading",
    name: "Reading",
    region: "Berkshire",
    postcodes: "RG1, RG2, RG4, RG5, RG6, RG7, RG8, RG9, RG10, RG30, RG31",
    areas: "Wokingham, Bracknell, Henley-on-Thames, Newbury, Maidenhead, Thatcham, Caversham, Earley",
    description: "Cheap car recovery in Reading & Berkshire. 24/7 breakdown recovery across all Reading postcodes and surrounding Thames Valley areas.",
    intro: "Reading is one of the UK's major commuter hubs, with the M4, A33, and A329(M) all converging nearby. Breakdowns on these routes leave thousands of drivers stranded every year. Our Berkshire recovery agents cover all Reading RG postcodes and extend into Wokingham, Bracknell, Newbury, and the wider Thames Valley region.",
    whyUs: "Our Reading agents cover the full Berkshire commuter belt — including the M4 corridor, A329(M), and the busy A33. We serve Caversham, Earley, Woodley, and extend into Wokingham and Bracknell, providing fast, professional recovery at fixed prices.",
    faq1Q: "Do you cover the M4 near Reading junctions 10-12?",
    faq1A: "Yes, we cover M4 junctions 10, 11, and 12 around Reading, as well as the A329(M) and all major routes in Berkshire.",
    faq2Q: "Can you recover my car in Reading and transport it to London?",
    faq2A: "Yes, we offer A-to-B transportation from Reading to London or any other destination. Enter your delivery address in the quote form for a full fixed-price quote.",
  },
  {
    slug: "milton-keynes",
    name: "Milton Keynes",
    region: "Buckinghamshire",
    postcodes: "MK1, MK2, MK3, MK4, MK5, MK6, MK7, MK8, MK9, MK10, MK11, MK12, MK13, MK14, MK15",
    areas: "Newport Pagnell, Bletchley, Wolverton, Bedford approach, Northampton approach, Olney, Stony Stratford",
    description: "Cheap car recovery in Milton Keynes & Buckinghamshire. 24/7 breakdown recovery across all MK postcodes and surrounding areas.",
    intro: "Milton Keynes's unique grid road system and its position on the M1 make it one of the UK's most distinctive driving environments. Whether you've broken down on the H-roads, the V-roads, or on the M1 nearby, our recovery agents cover all MK postcodes and extend into Newport Pagnell, Bletchley, and Wolverton.",
    whyUs: "Our Milton Keynes agents know the grid road system and are positioned to cover the city and the M1 corridor efficiently. We serve all MK postcodes from Central Milton Keynes out to the new estates and surrounding Buckinghamshire towns.",
    faq1Q: "Do you cover the M1 near Milton Keynes junctions 13-14?",
    faq1A: "Yes, M1 junctions 13 and 14 around Milton Keynes are key routes for our agents. All M1 recovery calls are treated as high priority.",
    faq2Q: "Do you recover cars on the Milton Keynes grid roads?",
    faq2A: "Yes, we cover all of Milton Keynes's H and V grid roads as well as the A5, A509, and surrounding local roads. Enter your grid road address in the quote form.",
  },
  {
    slug: "oxford",
    name: "Oxford",
    region: "Oxfordshire",
    postcodes: "OX1, OX2, OX3, OX4, OX14, OX15, OX16, OX18, OX25, OX26, OX28, OX29",
    areas: "Abingdon, Didcot, Witney, Banbury, Bicester, Kidlington, Headington, Cowley, Botley",
    description: "Cheap car recovery in Oxford & Oxfordshire. 24/7 breakdown recovery across all Oxford postcodes and surrounding Oxfordshire areas.",
    intro: "Oxford's historic city centre, busy ring road, and connections to the A34, M40, and A40 make breakdowns a common occurrence. Our Oxfordshire recovery agents cover all Oxford OX postcodes and extend into Abingdon, Didcot, Witney, Banbury, and Bicester. Professional, fixed-price recovery available 24 hours a day.",
    whyUs: "Our Oxford agents understand the city's unique driving environment — from the restricted city centre to the busy A34 bypass and M40 at Waterstock. We cover Headington, Cowley, Kidlington, and all surrounding Oxfordshire towns with fast, professional recovery.",
    faq1Q: "Do you cover the A34 and M40 near Oxford?",
    faq1A: "Yes, we cover the A34, M40 (junctions 8-9), A40 and all major routes around Oxford. The A34 is one of our most frequently served roads.",
    faq2Q: "Can you recover a car from Oxford city centre?",
    faq2A: "Yes, including within the Oxford Low Emission Zone where applicable. Our agents are familiar with Oxford's city centre restrictions and access routes.",
  },
  {
    slug: "cambridge",
    name: "Cambridge",
    region: "Cambridgeshire",
    postcodes: "CB1, CB2, CB3, CB4, CB5, CB21, CB22, CB23, CB24, CB25",
    areas: "Ely, Huntingdon, St Ives, Newmarket, Royston, Saffron Walden, Bar Hill, Cambourne",
    description: "Cheap car recovery in Cambridge & Cambridgeshire. 24/7 breakdown recovery across all Cambridge postcodes and surrounding areas.",
    intro: "Cambridge's busy A14, M11, and A1(M) connections see heavy daily traffic from commuters and HGVs. Breakdowns on these routes need fast, professional response. Our Cambridgeshire recovery agents cover all Cambridge CB postcodes and extend into Ely, Huntingdon, Newmarket, and the wider fens region.",
    whyUs: "Our Cambridge agents cover the city and all surrounding Cambridgeshire areas — from the Science Park in the north to the M11 junction 12 in the south. We're familiar with the narrow city streets as well as the A14 and M11 motorway sections, providing fast recovery across the full CB postcode area.",
    faq1Q: "Do you cover the A14 and M11 near Cambridge?",
    faq1A: "Yes, the A14 and M11 around Cambridge are key routes we serve regularly. All motorway and dual carriageway incidents are our top priority.",
    faq2Q: "Can you recover a car in Cambridge city centre with its narrow streets?",
    faq2A: "Yes, our agents are familiar with Cambridge city centre access routes and can reach most locations. Just provide your exact address in the quote form.",
  },
  {
    slug: "norwich",
    name: "Norwich",
    region: "Norfolk",
    postcodes: "NR1, NR2, NR3, NR4, NR5, NR6, NR7, NR8, NR9, NR10, NR13, NR14",
    areas: "Great Yarmouth, Dereham, Wymondham, Attleborough, Costessey, Sprowston, Thorpe St Andrew",
    description: "Cheap car recovery in Norwich & Norfolk. 24/7 breakdown recovery across all Norwich postcodes and surrounding Norfolk areas.",
    intro: "Norwich is Norfolk's principal city, connected to the rest of the UK via the A11, A47, and the Norwich Northern Distributor Road. Our Norfolk recovery agents cover all Norwich NR postcodes and extend into Great Yarmouth, Dereham, Wymondham, and the wider Norfolk countryside. Fixed-price recovery, 24 hours a day.",
    whyUs: "We cover Norwich city centre and all surrounding Norfolk towns and villages. Our agents are familiar with the A11 London corridor, the A47 cross-country route, and the Northern Distributor Road — ensuring fast response times across the region.",
    faq1Q: "Do you cover the A11 and A47 near Norwich?",
    faq1A: "Yes, we cover the A11, A47, and A140 around Norwich. These are regularly served routes for our Norfolk recovery agents.",
    faq2Q: "Do you recover cars in rural Norfolk areas outside Norwich?",
    faq2A: "Yes, our network extends across Norfolk including rural areas. Response times may vary in very remote locations, but we always provide coverage. Mention your rural location when getting your quote.",
  },
  {
    slug: "stoke-on-trent",
    name: "Stoke-on-Trent",
    region: "Staffordshire",
    postcodes: "ST1, ST2, ST3, ST4, ST5, ST6, ST7, ST8, ST11, ST12",
    areas: "Hanley, Burslem, Longton, Fenton, Newcastle-under-Lyme, Stafford, Stone, Leek, Uttoxeter",
    description: "Cheap car recovery in Stoke-on-Trent & Staffordshire. 24/7 breakdown recovery across all Stoke postcodes and surrounding areas.",
    intro: "Stoke-on-Trent spans five towns connected by the M6, A500 Queensway, and A50. Breakdowns anywhere across this urban spread need a knowledgeable local response. Our Staffordshire recovery agents cover all Stoke-on-Trent ST postcodes and extend into Newcastle-under-Lyme, Stafford, and the surrounding Staffordshire Moorlands.",
    whyUs: "Our Stoke agents cover all five towns — Hanley, Burslem, Tunstall, Longton, and Fenton — as well as Newcastle-under-Lyme and the M6 corridor. We're positioned to provide fast response times across this dispersed urban area and the surrounding rural Staffordshire.",
    faq1Q: "Do you cover the M6 near Stoke-on-Trent junctions 15-16?",
    faq1A: "Yes, M6 junctions 15 and 16 around Stoke are key recovery routes. All M6 motorway incidents are treated as our highest priority.",
    faq2Q: "Can you recover a car across all five Stoke towns?",
    faq2A: "Yes, we cover Hanley, Burslem, Tunstall, Longton, and Fenton as well as Newcastle-under-Lyme and all surrounding ST postcodes.",
  },
  {
    slug: "hull",
    name: "Hull",
    region: "East Yorkshire",
    postcodes: "HU1, HU2, HU3, HU4, HU5, HU6, HU7, HU8, HU9, HU10, HU13, HU14, HU15",
    areas: "Beverley, Brough, Goole, Hessle, Cottingham, Anlaby, Willerby, Elloughton, Withernsea",
    description: "Cheap car recovery in Hull & East Yorkshire. 24/7 breakdown recovery across all Hull postcodes and surrounding East Yorkshire areas.",
    intro: "Kingston upon Hull sits at the end of the M62 and is connected to Lincolnshire via the Humber Bridge. Its position means breakdowns can occur on some of the UK's longest motorway approaches. Our East Yorkshire recovery agents cover all Hull HU postcodes and extend into Beverley, Brough, Goole, and the East Yorkshire Wolds.",
    whyUs: "Our Hull agents cover the city and the wider East Yorkshire area — including the M62, A63, Humber Bridge approach, and all major local routes. We serve Cottingham, Hessle, Beverley, and Brough with the same fixed-price, 24/7 service as our other UK locations.",
    faq1Q: "Do you cover the Humber Bridge and A63 near Hull?",
    faq1A: "Yes, we cover the A63, A1033, M62 and Humber Bridge approach roads. If you break down on or near the bridge, stay safe and contact us immediately.",
    faq2Q: "Do you provide recovery on the A1033 and routes into East Yorkshire?",
    faq2A: "Yes, we cover the A1033, A164, A165 and surrounding East Yorkshire A-roads as well as the M62. Enter your collection address in the quote form for an instant price.",
  },
  {
    slug: "middlesbrough",
    name: "Middlesbrough",
    region: "Teesside",
    postcodes: "TS1, TS2, TS3, TS4, TS5, TS6, TS7, TS8, TS17, TS18, TS19, TS20, TS23, TS24",
    areas: "Stockton-on-Tees, Hartlepool, Darlington, Redcar, Billingham, Norton, Yarm, Thornaby",
    description: "Cheap car recovery in Middlesbrough & Teesside. 24/7 breakdown recovery across Middlesbrough and the wider Tees Valley.",
    intro: "Middlesbrough is the centre of Teesside's road network, with the A19, A66, and A174 all converging in the area. Our Teesside recovery agents cover all Middlesbrough TS postcodes and extend into Stockton, Hartlepool, Darlington, and Redcar. Professional fixed-price recovery, available 24/7 across the whole Tees Valley.",
    whyUs: "Our Middlesbrough agents cover the full Tees Valley — from Middlesbrough and Stockton in the west to Hartlepool on the coast. We're familiar with the A19, A66 coast route, and the Tees Crossing, providing rapid response times for all recovery types.",
    faq1Q: "Do you cover the A19 and A66 near Middlesbrough?",
    faq1A: "Yes, we cover the A19, A66, A174 and all major Teesside routes. Dual carriageway incidents are treated as priority calls.",
    faq2Q: "Do you cover recovery across the Tees Valley including Hartlepool?",
    faq2A: "Yes, our coverage extends across the full Tees Valley — Middlesbrough, Stockton, Hartlepool, Redcar and Darlington are all covered under the same fixed-price service.",
  },
  {
    slug: "swansea",
    name: "Swansea",
    region: "South Wales",
    postcodes: "SA1, SA2, SA3, SA4, SA5, SA6, SA7, SA8, SA9",
    areas: "Neath, Port Talbot, Llanelli, Ammanford, Gorseinon, Mumbles, Bridgend approach, Pontardawe",
    description: "Cheap car recovery in Swansea & South Wales. 24/7 breakdown recovery across all Swansea postcodes and surrounding West Wales areas.",
    intro: "Swansea is South Wales's second city, with the M4, A48, and A483 all passing through or near the city. Whether you break down on the motorway, in Swansea city centre, or on the scenic Gower Peninsula roads, our South Wales recovery agents are ready to help. We cover all Swansea SA postcodes and extend into Neath, Port Talbot, Llanelli, and Ammanford.",
    whyUs: "Our Swansea agents cover the city and the wider west Wales area — including Neath Port Talbot, Llanelli, and the Gower. We're familiar with the M4 junctions around Swansea, the A483, and all local routes, providing fast professional recovery at fixed prices.",
    faq1Q: "Do you cover the M4 near Swansea junctions 42-47?",
    faq1A: "Yes, we cover M4 junctions 42-47 around Swansea and the A48 and A483 corridors. All M4 incidents in this area are treated as high priority.",
    faq2Q: "Can you recover my car from the Gower Peninsula?",
    faq2A: "Yes, we cover the Gower Peninsula including Mumbles, Rhossili approaches, and Gower villages. Response times in remote areas may be slightly longer — mention your location when getting your quote.",
  },
  {
    slug: "exeter",
    name: "Exeter",
    region: "Devon",
    postcodes: "EX1, EX2, EX3, EX4, EX5, EX6, EX7, EX8, EX9",
    areas: "Exmouth, Topsham, Crediton, Newton Abbot, Dawlish, Teignmouth, Honiton, Tiverton",
    description: "Cheap car recovery in Exeter & Devon. 24/7 breakdown recovery across all Exeter postcodes and surrounding Devon areas.",
    intro: "Exeter sits at the junction of the M5 and A30 — Devon's main arteries heading west into Cornwall and north to the Midlands. Breakdowns here can leave you stranded far from help, especially on the A30 dual carriageway or the quieter rural routes. Our Devon recovery agents cover all Exeter EX postcodes and extend into Exmouth, Newton Abbot, Tiverton, and Honiton.",
    whyUs: "Our Exeter agents cover the city and the wider Devon area — including the M5 junction 30 approach, the A30, and the A38 Devon Expressway south towards Plymouth. We serve Exmouth, Topsham, Crediton, and all surrounding EX postcodes with professional, fixed-price recovery.",
    faq1Q: "Do you cover the M5 and A30 near Exeter?",
    faq1A: "Yes, we cover the M5 (junction 29-30), A30, A38, and all major routes around Exeter. Motorway and dual carriageway recovery is treated as our highest priority.",
    faq2Q: "Can you recover a car from rural Devon near Exeter?",
    faq2A: "Yes, our Devon agents cover rural areas as well as main roads. For very remote locations, please mention this in your quote so we can ensure the right recovery vehicle is dispatched.",
  },
  {
    slug: "brighton",
    name: "Brighton",
    region: "East Sussex",
    postcodes: "BN1, BN2, BN3, BN41, BN42, BN43, BN44, BN45",
    areas: "Hove, Worthing, Shoreham-by-Sea, Lewes, Burgess Hill, Haywards Heath, Portslade, Lancing",
    description: "Cheap car recovery in Brighton & East Sussex. 24/7 breakdown recovery across Brighton, Hove, and surrounding coastal areas.",
    intro: "Brighton's coastal location and busy A23, A27, and M23 connections make it a common location for breakdowns. Whether you're stuck in Brighton city centre, on the A27 coastal road, or on the M23 approaching from London, our East Sussex recovery agents are ready to help. Fixed prices, instant SMS quotes, 24/7.",
    whyUs: "Our Brighton agents cover the full coastal strip — from Worthing in the west to Lewes and Eastbourne approaches in the east. We serve Hove, Shoreham, Burgess Hill, and all BN postcodes with professional, fully insured recovery vehicles.",
    faq1Q: "Do you cover the A23 and M23 near Brighton?",
    faq1A: "Yes, we cover the M23, A23, A27 and all major routes around Brighton and the East Sussex coast. The M23/A23 corridor from London to Brighton is a regularly served route.",
    faq2Q: "Can you recover a car from Brighton seafront or city centre?",
    faq2A: "Yes, including the seafront areas and parking locations in central Brighton. Enter your exact address in the quote form and we'll calculate your fixed price.",
  },
  {
    slug: "bournemouth",
    name: "Bournemouth",
    region: "Dorset",
    postcodes: "BH1, BH2, BH3, BH4, BH5, BH6, BH7, BH8, BH9, BH10, BH11, BH12, BH13",
    areas: "Poole, Christchurch, Wimborne, Ferndown, Ringwood, Verwood, Boscombe, Westbourne",
    description: "Cheap car recovery in Bournemouth & Dorset. 24/7 breakdown recovery across all Bournemouth postcodes and surrounding coastal areas.",
    intro: "Bournemouth and Poole form one of the South Coast's largest urban areas, connected to the motorway network via the A338 Spur Road and M27. Breakdowns here — whether in the town centre, on the A338, or on the coastal routes — are handled swiftly by our Dorset recovery agents. We cover all BH postcodes and extend into Wimborne, Ferndown, and Ringwood.",
    whyUs: "Our Bournemouth agents cover the coastal conurbation from Christchurch to Poole and north towards Wimborne. We're familiar with the A338, A31, and the routes connecting Bournemouth to the M27 — ensuring rapid coverage across the full BH postcode area.",
    faq1Q: "Do you cover the A338 Bournemouth Spur Road and M27 approach?",
    faq1A: "Yes, the A338 and M27 approach roads are regularly served recovery routes. All dual carriageway and major A-road incidents are our top priority.",
    faq2Q: "Can you recover a car from Poole or Christchurch as well as Bournemouth?",
    faq2A: "Yes, our coverage extends across Poole, Christchurch, Wimborne, and Ferndown — all under the same fixed-price service as Bournemouth itself.",
  },
  {
    slug: "ipswich",
    name: "Ipswich",
    region: "Suffolk",
    postcodes: "IP1, IP2, IP3, IP4, IP5, IP6, IP7, IP8, IP9, IP10",
    areas: "Felixstowe, Woodbridge, Stowmarket, Needham Market, Hadleigh, Kesgrave, Martlesham, Capel St Mary",
    description: "Cheap car recovery in Ipswich & Suffolk. 24/7 breakdown recovery across all Ipswich postcodes and surrounding Suffolk areas.",
    intro: "Ipswich is Suffolk's county town, connected to the A14, A12, and the wider East Anglian road network. Breakdowns on the busy A14 between Ipswich and Cambridge or on the A12 towards London are particularly common. Our Suffolk recovery agents cover all Ipswich IP postcodes and extend into Felixstowe, Woodbridge, and Stowmarket.",
    whyUs: "Our Ipswich agents are positioned to cover the A14, A12, and local Ipswich roads efficiently. We serve Felixstowe port approaches, the Ipswich town centre, Kesgrave, and all surrounding IP postcodes with professional recovery at transparent fixed prices.",
    faq1Q: "Do you cover the A14 and A12 near Ipswich?",
    faq1A: "Yes, the A14 and A12 around Ipswich are key recovery routes. These dual carriageway incidents are treated as highest priority calls.",
    faq2Q: "Can you recover a car near Felixstowe port?",
    faq2A: "Yes, we cover the Felixstowe area including port approach roads. If access is restricted in certain port zones, please mention this when getting your quote.",
  },
  {
    slug: "chester",
    name: "Chester",
    region: "Cheshire",
    postcodes: "CH1, CH2, CH3, CH4, CH5, CH6, CH7, CH8",
    areas: "Ellesmere Port, Wrexham, Flint, Deeside, Neston, Frodsham, Helsby, Blacon, Saltney",
    description: "Cheap car recovery in Chester & Cheshire. 24/7 breakdown recovery across all Chester postcodes and surrounding North Wales border areas.",
    intro: "Chester sits at the crossroads of Cheshire and North Wales, with the M53, M56, and A55 North Wales Expressway all nearby. Breakdowns here can leave you stranded between England and Wales. Our Cheshire recovery agents cover all Chester CH postcodes and extend into Ellesmere Port, Wrexham, Deeside, and Flint.",
    whyUs: "Our Chester agents cover both sides of the English-Welsh border — including the A55 across Deeside into North Wales, the M56, M53, and all local Chester routes. We serve Ellesmere Port, Neston, Frodsham, and the full CH postcode area with professional recovery.",
    faq1Q: "Do you cover the M53, M56, and A55 near Chester?",
    faq1A: "Yes, we cover the M53, M56, A55, and A483 around Chester and the surrounding area including into North Wales. Motorway recovery is our highest priority.",
    faq2Q: "Can you recover a car across the Welsh border from Chester?",
    faq2A: "Yes, we cover both Cheshire and the North Wales border area including Wrexham, Flint, and Deeside under the same fixed-price service.",
  },
  {
    slug: "york",
    name: "York",
    region: "North Yorkshire",
    postcodes: "YO1, YO10, YO19, YO23, YO24, YO26, YO30, YO31, YO32",
    areas: "Selby, Malton, Pocklington, Stamford Bridge, Haxby, Skelton, Clifton, Fulford",
    description: "Cheap car recovery in York & North Yorkshire. 24/7 breakdown recovery across all York postcodes and surrounding Yorkshire areas.",
    intro: "York is a historic city at the heart of North Yorkshire, connected to the A64, A19, and A59. Heavy tourist traffic and narrow historic streets make it a frequent location for breakdowns. Our North Yorkshire recovery agents cover all York YO postcodes and extend into Selby, Malton, and Pocklington.",
    whyUs: "Our York agents know the city's one-way systems, the historic centre restrictions, and the surrounding A64 and A19 trunk roads. We cover Selby, Haxby, Skelton, and all YO postcodes with professional recovery at fixed prices.",
    faq1Q: "Do you cover the A64 and A19 near York?",
    faq1A: "Yes, the A64 (York to Scarborough) and A19 (York to Selby and beyond) are regularly served routes for our recovery agents.",
    faq2Q: "Can you recover a car from York city centre?",
    faq2A: "Yes, including the historic city centre. Our agents are familiar with York's restricted zones and access routes. Provide your exact location in the quote form.",
  },
  {
    slug: "doncaster",
    name: "Doncaster",
    region: "South Yorkshire",
    postcodes: "DN1, DN2, DN3, DN4, DN5, DN6, DN7, DN8, DN9, DN10, DN11, DN12",
    areas: "Rotherham, Barnsley, Mexborough, Bentley, Thorne, Bawtry, Conisbrough, Hatfield",
    description: "Cheap car recovery in Doncaster & South Yorkshire. 24/7 breakdown recovery across all Doncaster postcodes and surrounding areas.",
    intro: "Doncaster sits at the junction of the M18, M180, and A1(M) — one of the UK's busiest motorway intersections. Breakdowns here are common, and our South Yorkshire recovery agents are positioned to respond rapidly across all Doncaster DN postcodes and into the surrounding area including Rotherham and Barnsley.",
    whyUs: "Our Doncaster agents cover the full DN postcode area and the surrounding motorway network. We're familiar with the M18/M180 junction, the A1(M) through Doncaster, and all local routes — providing fast professional recovery across South Yorkshire.",
    faq1Q: "Do you cover the M18, M180, and A1(M) near Doncaster?",
    faq1A: "Yes, the M18, M180, and A1(M) near Doncaster are among our most frequently served motorway routes. All motorway incidents are our top priority.",
    faq2Q: "Do you cover Rotherham and Barnsley as well as Doncaster?",
    faq2A: "Yes, our South Yorkshire coverage extends into Rotherham, Barnsley, Mexborough, and all surrounding DN and S postcodes under the same fixed-price service.",
  },
  {
    slug: "wakefield",
    name: "Wakefield",
    region: "West Yorkshire",
    postcodes: "WF1, WF2, WF3, WF4, WF5, WF6, WF7, WF8, WF9, WF10, WF11, WF12, WF13, WF14, WF15, WF16, WF17",
    areas: "Castleford, Pontefract, Ossett, Dewsbury, Horbury, Normanton, Knottingley, Featherstone",
    description: "Cheap car recovery in Wakefield & West Yorkshire. 24/7 breakdown recovery across all Wakefield postcodes and surrounding areas.",
    intro: "Wakefield's location on the M1 and M62 puts it at the centre of West Yorkshire's motorway network. Breakdowns on these busy routes are frequent, and our West Yorkshire recovery agents cover all Wakefield WF postcodes from the city centre to Castleford, Pontefract, Dewsbury, and Ossett.",
    whyUs: "Our Wakefield agents cover the full WF postcode area and are familiar with the M1 junctions 39-41 around Wakefield, the M62, and the A638 route. We serve Castleford, Normanton, Horbury, Ossett, and all surrounding areas with professional fixed-price recovery.",
    faq1Q: "Do you cover the M1 and M62 near Wakefield?",
    faq1A: "Yes, we cover M1 junctions 39-41 and the M62 around Wakefield. All motorway incidents are treated as our highest priority.",
    faq2Q: "Do you cover recovery near Castleford and Pontefract?",
    faq2A: "Yes, Castleford, Pontefract, Knottingley, and all WF postcodes are covered under the same service as Wakefield itself.",
  },
  {
    slug: "luton",
    name: "Luton",
    region: "Bedfordshire",
    postcodes: "LU1, LU2, LU3, LU4, LU5, LU6, LU7",
    areas: "Dunstable, Harpenden, Leighton Buzzard, Hitchin, Ampthill, Flitwick, Biggleswade",
    description: "Cheap car recovery in Luton & Bedfordshire. 24/7 breakdown recovery across all Luton postcodes and surrounding Bedfordshire areas.",
    intro: "Luton is a major hub town north of London on the M1 and A505, with Luton Airport adding significant traffic to the area. Breakdowns near the M1 junctions or the busy airport approach roads need fast, local response. Our Bedfordshire recovery agents cover all Luton LU postcodes and extend into Dunstable, Harpenden, and Leighton Buzzard.",
    whyUs: "Our Luton agents cover the M1 junctions 9-11, the A505, A6, and the airport approach roads. We serve Dunstable, Harpenden, Ampthill, and the full LU postcode area with professional fixed-price recovery available 24/7.",
    faq1Q: "Do you cover the M1 near Luton junctions 9-11?",
    faq1A: "Yes, M1 junctions 9-11 around Luton are key recovery routes. All M1 incidents are treated as priority calls.",
    faq2Q: "Can you recover a car near Luton Airport?",
    faq2A: "Yes, we cover the Luton Airport approach roads and the wider airport area. If you need recovery from a restricted zone, mention this when getting your quote.",
  },
  {
    slug: "peterborough",
    name: "Peterborough",
    region: "Cambridgeshire",
    postcodes: "PE1, PE2, PE3, PE4, PE6, PE7, PE8, PE9",
    areas: "Stamford, Spalding, Huntingdon, March, Whittlesey, Yaxley, Market Deeping, Eye",
    description: "Cheap car recovery in Peterborough & Cambridgeshire. 24/7 breakdown recovery across all Peterborough postcodes and surrounding Fens areas.",
    intro: "Peterborough sits on the A1(M) corridor and the A47 cross-country route, making it a significant transit point for North-South and East-West journeys. Breakdowns on these busy routes need a fast response. Our agents cover all Peterborough PE postcodes and extend into Stamford, Spalding, Huntingdon, and the Fenland.",
    whyUs: "Our Peterborough agents cover the A1(M), A47, A15, and local Peterborough routes. We serve Stamford, March, Whittlesey, and all surrounding PE postcodes with the same professional, fixed-price recovery service available across our UK network.",
    faq1Q: "Do you cover the A1(M) near Peterborough?",
    faq1A: "Yes, the A1(M) through Peterborough (junctions 17-18) and the A47 are key routes we serve regularly. Dual carriageway incidents are our top priority.",
    faq2Q: "Do you cover the Fens and rural areas around Peterborough?",
    faq2A: "Yes, we cover rural Fenland as well as main roads. Response times may be slightly longer in very remote fen areas — mention your location when quoting.",
  },
  {
    slug: "gloucester",
    name: "Gloucester",
    region: "Gloucestershire",
    postcodes: "GL1, GL2, GL3, GL4, GL7, GL10, GL11, GL12, GL13, GL14, GL15",
    areas: "Cheltenham, Stroud, Cirencester, Tewkesbury, Lydney, Dursley, Nailsworth, Forest of Dean",
    description: "Cheap car recovery in Gloucester & Gloucestershire. 24/7 breakdown recovery across all Gloucester postcodes and surrounding areas.",
    intro: "Gloucester and Cheltenham sit alongside the M5 in Gloucestershire, with the A40, A417, and A38 providing key routes through the county. Breakdowns on the M5 or the cross-Cotswold A417 road are common, and our Gloucestershire recovery agents cover all GL postcodes from the city to the Forest of Dean and the Cotswold fringe.",
    whyUs: "Our Gloucester agents cover the M5 (junctions 11-12), the A417, A40, and A38, as well as Cheltenham, Stroud, Cirencester, and the Forest of Dean. We provide professional recovery across all of Gloucestershire's varied terrain at fixed prices.",
    faq1Q: "Do you cover the M5 near Gloucester and Cheltenham?",
    faq1A: "Yes, M5 junctions 11 and 12 around Gloucester and Cheltenham are key recovery routes we serve regularly.",
    faq2Q: "Can you recover a car from the Cotswolds or Forest of Dean?",
    faq2A: "Yes, we cover the Cotswolds, Forest of Dean, and rural Gloucestershire. For remote areas, please mention your location when getting your quote.",
  },
  {
    slug: "worcester",
    name: "Worcester",
    region: "Worcestershire",
    postcodes: "WR1, WR2, WR3, WR4, WR5, WR6, WR7, WR8, WR9, WR10, WR11, WR14",
    areas: "Malvern, Pershore, Redditch, Evesham, Droitwich, Bromsgrove, Kidderminster, Upton upon Severn",
    description: "Cheap car recovery in Worcester & Worcestershire. 24/7 breakdown recovery across all Worcester postcodes and surrounding areas.",
    intro: "Worcester sits at the heart of Worcestershire on the M5 corridor, with the A449, A44, and A38 all passing through or nearby. Our recovery agents cover all Worcester WR postcodes and extend into Malvern, Pershore, Evesham, Droitwich, and Redditch — providing fast, fixed-price recovery across the full county.",
    whyUs: "Our Worcester agents cover the M5 junctions around the city, the A449, and all local Worcestershire routes. We serve Malvern, Redditch, Kidderminster, and Evesham with the same professional service as the city itself.",
    faq1Q: "Do you cover the M5 near Worcester?",
    faq1A: "Yes, the M5 through Worcestershire and A449 are regularly served routes. All motorway incidents are our highest priority.",
    faq2Q: "Can you recover a car from the Malvern Hills area?",
    faq2A: "Yes, we cover the Malvern Hills area and surrounding rural Worcestershire. Mention your specific location in the quote form for an accurate fixed price.",
  },
  {
    slug: "shrewsbury",
    name: "Shrewsbury",
    region: "Shropshire",
    postcodes: "SY1, SY2, SY3, SY4, SY5, SY6",
    areas: "Telford, Newport, Market Drayton, Ludlow, Bridgnorth, Oswestry, Whitchurch, Shifnal",
    description: "Cheap car recovery in Shrewsbury & Shropshire. 24/7 breakdown recovery across all Shrewsbury postcodes and surrounding areas.",
    intro: "Shrewsbury is Shropshire's county town, connected to the Midlands via the A5, M54, and A49. The town's position on the River Severn and surrounding rural roads mean breakdowns can happen far from the nearest garage. Our Shropshire recovery agents cover all SY postcodes and extend into Telford, Ludlow, Oswestry, and Market Drayton.",
    whyUs: "Our Shrewsbury agents cover the A5 Telford link, A49, A458, and all local Shropshire routes. We serve Telford, Newport, Bridgnorth, Ludlow, and rural Shropshire with professional fixed-price recovery.",
    faq1Q: "Do you cover the A5 and M54 near Shrewsbury?",
    faq1A: "Yes, we cover the A5, M54, A49, and all major routes around Shrewsbury and Telford. The M54 corridor is a key recovery route we serve regularly.",
    faq2Q: "Can you recover a car from rural Shropshire?",
    faq2A: "Yes, our coverage extends across rural Shropshire. Response times may be longer in very remote areas — mention your location when requesting your quote.",
  },
  {
    slug: "aberdeen",
    name: "Aberdeen",
    region: "North East Scotland",
    postcodes: "AB10, AB11, AB12, AB13, AB14, AB15, AB16, AB21, AB22, AB23, AB24, AB25",
    areas: "Stonehaven, Portlethen, Inverurie, Dyce, Westhill, Ellon, Bridge of Don, Banchory",
    description: "Cheap car recovery in Aberdeen & North East Scotland. 24/7 breakdown recovery across all Aberdeen postcodes and surrounding areas.",
    intro: "Aberdeen is Scotland's third city and the hub of the North Sea oil industry, with the A90, A96, and the new Aberdeen Western Peripheral Route (AWPR) carrying significant traffic. Breakdowns here — whether on the AWPR bypass or in the city centre — are handled by our North East Scotland recovery agents, covering all AB postcodes and extending into Stonehaven, Inverurie, and Westhill.",
    whyUs: "Our Aberdeen agents cover the AWPR, A90, A96, and all local Aberdeen routes. We're familiar with the oil industry access roads, Dyce Airport approaches, and the city's unique geography — providing fast, professional recovery across the full AB postcode area.",
    faq1Q: "Do you cover the AWPR and A90 near Aberdeen?",
    faq1A: "Yes, the Aberdeen Western Peripheral Route and A90 are key recovery routes we serve regularly. All dual carriageway incidents are our highest priority.",
    faq2Q: "Do you cover recovery near Aberdeen harbour and the oil industry areas?",
    faq2A: "Yes, we cover all Aberdeen postcodes including harbour and industrial areas. Mention any access restrictions when getting your quote.",
  },
  {
    slug: "dundee",
    name: "Dundee",
    region: "Tayside",
    postcodes: "DD1, DD2, DD3, DD4, DD5, DD6",
    areas: "Perth, Arbroath, Forfar, Montrose, Broughty Ferry, Carnoustie, Monifieth, Cupar",
    description: "Cheap car recovery in Dundee & Tayside. 24/7 breakdown recovery across all Dundee postcodes and surrounding Tayside areas.",
    intro: "Dundee sits on the Tay estuary, connected to the A90 dual carriageway north to Aberdeen and south to Edinburgh via the Queensferry Crossing. The Tay Road Bridge and the A92 coastal route add to the complexity of the local network. Our Tayside recovery agents cover all Dundee DD postcodes and extend into Perth, Arbroath, and Forfar.",
    whyUs: "Our Dundee agents cover the A90, A92, A85, Tay Road Bridge approaches, and all local Dundee routes. We serve Perth, Arbroath, Carnoustie, and the full DD postcode area with the same professional service you'd expect anywhere in our UK network.",
    faq1Q: "Do you cover the A90 and Tay Bridge approaches near Dundee?",
    faq1A: "Yes, the A90 and Tay Road Bridge approach roads are regularly served routes. If you break down on the bridge itself, contact us and we'll coordinate the appropriate response.",
    faq2Q: "Can you recover a car from Perth or Arbroath near Dundee?",
    faq2A: "Yes, our coverage extends into Perth, Arbroath, Forfar, and the surrounding Tayside area under the same fixed-price service.",
  },
  {
    slug: "colchester",
    name: "Colchester",
    region: "Essex",
    postcodes: "CO1, CO2, CO3, CO4, CO5, CO6, CO7, CO8, CO9, CO10",
    areas: "Chelmsford, Braintree, Clacton-on-Sea, Harwich, Sudbury, Witham, Halstead, Mersea Island",
    description: "Cheap car recovery in Colchester & Essex. 24/7 breakdown recovery across all Colchester postcodes and surrounding Essex areas.",
    intro: "Colchester is one of Britain's oldest recorded towns, situated on the A12 between London and the Essex coast. The A12, A120, and A134 converge around the town, making it a frequent breakdown location for drivers heading to Harwich port or the Essex coast. Our Essex recovery agents cover all Colchester CO postcodes and extend into Chelmsford, Braintree, and Clacton.",
    whyUs: "Our Colchester agents are positioned to cover the A12, A120, and all local Essex routes efficiently. We serve Braintree, Clacton, Harwich, and the surrounding CO postcode area with professional recovery at transparent fixed prices.",
    faq1Q: "Do you cover the A12 and A120 near Colchester?",
    faq1A: "Yes, the A12 and A120 around Colchester are key recovery routes we serve regularly. Dual carriageway incidents are treated as our top priority.",
    faq2Q: "Can you recover a car heading to Harwich port from Colchester?",
    faq2A: "Yes, we cover the Harwich area and the A120 port approach road. If you're heading to catch a ferry, please let us know so we can prioritise your recovery.",
  },
  {
    slug: "lancaster",
    name: "Lancaster",
    region: "Lancashire",
    postcodes: "LA1, LA2, LA3, LA4, LA5",
    areas: "Morecambe, Carnforth, Heysham, Garstang, Caton, Halton, Galgate, Silverdale",
    description: "Cheap car recovery in Lancaster & Lancashire. 24/7 breakdown recovery across all Lancaster postcodes and surrounding North Lancashire areas.",
    intro: "Lancaster sits on the M6 between Preston and the Lake District, making it a gateway town for both local and long-distance travellers. Breakdowns on the M6 near Lancaster or on the A6 through the town are common. Our Lancashire recovery agents cover all Lancaster LA postcodes and extend into Morecambe, Carnforth, and Heysham.",
    whyUs: "Our Lancaster agents cover M6 junctions 33-35, the A6, and all local Lancaster and Morecambe routes. We serve Heysham port approaches, Carnforth, and the full LA postcode area with professional fixed-price recovery.",
    faq1Q: "Do you cover the M6 near Lancaster junctions 33-35?",
    faq1A: "Yes, M6 junctions 33-35 around Lancaster are key recovery routes. All M6 incidents are our highest priority.",
    faq2Q: "Can you recover a car near Heysham port?",
    faq2A: "Yes, we cover the Heysham port area and approach roads. If you have a ferry connection to make, mention this in your quote request.",
  },
  {
    slug: "carlisle",
    name: "Carlisle",
    region: "Cumbria",
    postcodes: "CA1, CA2, CA3, CA4, CA5, CA6, CA7, CA8",
    areas: "Penrith, Workington, Whitehaven, Wigton, Brampton, Longtown, Gretna approach, Dalston",
    description: "Cheap car recovery in Carlisle & Cumbria. 24/7 breakdown recovery across all Carlisle postcodes and surrounding Cumbria areas.",
    intro: "Carlisle is the most northerly English city, sitting on the M6 at the gateway to Scotland. Breakdowns here — whether on the M6, the A69 to Newcastle, or the A7 heading to Scotland — need a fast local response. Our Cumbria recovery agents cover all Carlisle CA postcodes and extend into Penrith, Wigton, and Brampton.",
    whyUs: "Our Carlisle agents cover M6 junctions 43-44, the A69, A7, A595, and all local Cumbrian routes. We serve Penrith, Wigton, Brampton, and the surrounding CA postcode area with professional, fixed-price recovery.",
    faq1Q: "Do you cover the M6 near Carlisle junctions 43-44?",
    faq1A: "Yes, M6 junctions 43 and 44 around Carlisle are key recovery routes. All M6 motorway incidents are treated as our highest priority.",
    faq2Q: "Can you recover a car across the Scottish border near Carlisle?",
    faq2A: "Yes, we cover the Gretna area and can assist drivers just across the Scottish border. For further Scottish coverage, our Scottish agents at Glasgow and Edinburgh can assist.",
  },
  {
    slug: "wigan",
    name: "Wigan",
    region: "Greater Manchester",
    postcodes: "WN1, WN2, WN3, WN4, WN5, WN6, WN7, WN8",
    areas: "Leigh, Skelmersdale, Ormskirk, Standish, Hindley, Golborne, Ashton-in-Makerfield, Ince",
    description: "Cheap car recovery in Wigan & Greater Manchester. 24/7 breakdown recovery across all Wigan postcodes and surrounding areas.",
    intro: "Wigan sits on the M6 and M58, connecting Manchester to the north and the wider North West. Breakdowns on these busy routes are common. Our Greater Manchester recovery agents cover all Wigan WN postcodes and extend into Leigh, Skelmersdale, Ormskirk, and Ashton-in-Makerfield.",
    whyUs: "Our Wigan agents cover M6 junctions 25-27, the M58, A49, A573, and all local Wigan routes. We serve Leigh, Standish, Golborne, and the full WN postcode area with professional fixed-price recovery 24 hours a day.",
    faq1Q: "Do you cover the M6 and M58 near Wigan?",
    faq1A: "Yes, M6 junctions 25-27 and the M58 around Wigan are key recovery routes we serve regularly. All motorway incidents are our top priority.",
    faq2Q: "Do you cover Leigh and Skelmersdale as well as Wigan?",
    faq2A: "Yes, Leigh, Skelmersdale, Ormskirk, and all WN postcodes are covered under the same fixed-price service as Wigan itself.",
  },
  {
    slug: "warrington",
    name: "Warrington",
    region: "Cheshire",
    postcodes: "WA1, WA2, WA3, WA4, WA5, WA6, WA7, WA8, WA9, WA10, WA11, WA12, WA13, WA14, WA15, WA16",
    areas: "Runcorn, Widnes, Frodsham, Lymm, Culcheth, Newton-le-Willows, Irlam, Altrincham",
    description: "Cheap car recovery in Warrington & Cheshire. 24/7 breakdown recovery across all Warrington postcodes and surrounding areas.",
    intro: "Warrington is one of the UK's busiest motorway junctions — the M6, M56, and M62 all meet nearby, making it a key interchange between the North West, Midlands, and Trans-Pennine corridors. Our Cheshire recovery agents cover all Warrington WA postcodes and extend into Runcorn, Widnes, Frodsham, and Lymm.",
    whyUs: "Our Warrington agents are positioned to cover the M6, M56, M62, and A49 efficiently. We serve Runcorn, Widnes, Newton-le-Willows, Altrincham, and the full WA postcode area with fast, professional recovery at fixed prices.",
    faq1Q: "Do you cover the M6, M56, and M62 near Warrington?",
    faq1A: "Yes, the M6 junctions 20-22, M56, and M62 around Warrington are among our most frequently served routes. All motorway incidents are our highest priority.",
    faq2Q: "Do you cover Runcorn and Widnes as well as Warrington?",
    faq2A: "Yes, Runcorn, Widnes, Frodsham, and all WA postcodes are covered under the same service, including the Silver Jubilee Bridge approach roads.",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}
